name: Go Example
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - name: Run benchmark
        run: cd examples/go && go test -bench 'BenchmarkFib' | tee output.txt

      - name: Store benchmark result
        uses: ./
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: examples/go/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@j3hempsey'

      - name: Store benchmark result - separate results repo
        uses: ./
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: examples/go/output.txt
          github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@j3hempsey'
          gh-repository: 'github.com/j3hempsey-actions/github-action-benchmark-results'
